// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptimizePro.Painel;

#nullable disable

namespace OptimizePro.Painel.Migrations
{
    [DbContext(typeof(PainelDbContext))]
    partial class PainelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OptimizePro.Painel.ConfiguracaoDeFaturamento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("LimiteDeUsuariosNoPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(7)
                        .HasColumnName("limite_de_usuarios_no_plano");

                    b.Property<decimal>("ValorBaseMensal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("valor_base_mensal");

                    b.Property<decimal>("ValorPorUsuarioExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("valor_por_usuario_extra");

                    b.HasKey("Id");

                    b.ToTable("painel_faturamento", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Painel.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<bool>("EhAdministrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eh_administrador");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("login");

                    b.Property<string>("ModulosLiberados")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("modulos_liberados");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("senha_hash");

                    b.Property<byte[]>("SenhaSal")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("senha_sal");

                    b.Property<DateTime?>("UltimoLoginEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("ultimo_login_em");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("painel_usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
