// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OptimizePro.Central;

#nullable disable

namespace OptimizePro.Central.Migrations
{
    [DbContext(typeof(CentralDbContext))]
    [Migration("20260910134351_InicialCentral")]
    partial class InicialCentral
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptimizePro.Central.Instalacao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<byte[]>("ChaveDeApiHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("chave_de_api_hash");

                    b.Property<long>("ClienteIdHash")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id_hash");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("NomeDaFabrica")
                        .HasColumnType("text")
                        .HasColumnName("nome_da_fabrica");

                    b.Property<DateTime?>("UltimaSincronizacaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_sincronizacao_em");

                    b.HasKey("Id");

                    b.HasIndex("ClienteIdHash")
                        .IsUnique();

                    b.ToTable("instalacoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
