// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptimizePro.Data;

#nullable disable

namespace OptimizePro.Data.Migrations
{
    [DbContext(typeof(OptimizeDbContext))]
    [Migration("20260910022817_AdicionaAssinaturaDeHistoricoNaMaquina")]
    partial class AdicionaAssinaturaDeHistoricoNaMaquina
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OptimizePro.Data.Entidades.ConfiguracaoApp", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("TEXT")
                        .HasColumnName("chave");

                    b.Property<string>("Valor")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("Chave");

                    b.ToTable("configuracao_app", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.EncaixeGuardado", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("TEXT")
                        .HasColumnName("chave");

                    b.Property<double?>("Aproveitamento")
                        .HasColumnType("REAL")
                        .HasColumnName("aproveitamento");

                    b.Property<string>("Assinatura")
                        .HasColumnType("TEXT")
                        .HasColumnName("assinatura");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<double>("Consumo")
                        .HasColumnType("REAL")
                        .HasColumnName("consumo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<double?>("Espaco")
                        .HasColumnType("REAL")
                        .HasColumnName("espaco");

                    b.Property<double?>("LarguraTecido")
                        .HasColumnType("REAL")
                        .HasColumnName("largura_tecido");

                    b.Property<double?>("Margem")
                        .HasColumnType("REAL")
                        .HasColumnName("margem");

                    b.Property<string>("PecasJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("pecas");

                    b.Property<string>("PosicoesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("posicoes");

                    b.Property<string>("Receita")
                        .HasColumnType("TEXT")
                        .HasColumnName("receita");

                    b.HasKey("Chave");

                    b.ToTable("encaixe_guardados", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.EncaixeHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double?>("Aproveitamento")
                        .HasColumnType("REAL")
                        .HasColumnName("aproveitamento");

                    b.Property<string>("Assinatura")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assinatura");

                    b.Property<double?>("Consumo")
                        .HasColumnType("REAL")
                        .HasColumnName("consumo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("features");

                    b.Property<double?>("LarguraTecido")
                        .HasColumnType("REAL")
                        .HasColumnName("largura_tecido");

                    b.Property<int?>("Pecas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pecas");

                    b.Property<string>("PlacarJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("placar");

                    b.Property<string>("Receita")
                        .HasColumnType("TEXT")
                        .HasColumnName("receita");

                    b.Property<int?>("Tentativas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tentativas");

                    b.HasKey("Id");

                    b.ToTable("encaixe_historico", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.EncaixeReceita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Assinatura")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assinatura");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Receita")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("receita");

                    b.Property<int>("Usos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("usos");

                    b.Property<int>("Vitorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("vitorias");

                    b.HasKey("Id");

                    b.HasIndex("Assinatura", "Receita")
                        .IsUnique();

                    b.ToTable("encaixe_receitas", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.EncaixeRedePesos", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("Exemplos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("exemplos");

                    b.Property<string>("PesosJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pesos");

                    b.HasKey("Id");

                    b.ToTable("encaixe_rede_pesos", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Maquina", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ArquivoLogAoVivo")
                        .HasColumnType("TEXT")
                        .HasColumnName("arquivo_log_ao_vivo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CaminhoEstatisticasDeTinta")
                        .HasColumnType("TEXT")
                        .HasColumnName("caminho_estatisticas_de_tinta");

                    b.Property<string>("CaminhoHistorico")
                        .HasColumnType("TEXT")
                        .HasColumnName("caminho_historico");

                    b.Property<string>("CaminhoListaDeTrabalhos")
                        .HasColumnType("TEXT")
                        .HasColumnName("caminho_lista_de_trabalhos");

                    b.Property<DateTime?>("DescobertaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("descoberta_em");

                    b.Property<bool>("Habilitada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitada");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT")
                        .HasColumnName("ip");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("manual")
                        .HasColumnName("origem");

                    b.Property<string>("PastaLogAoVivo")
                        .HasColumnType("TEXT")
                        .HasColumnName("pasta_log_ao_vivo");

                    b.Property<string>("PastaLogDeStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("pasta_log_de_status");

                    b.Property<string>("PastaPreview")
                        .HasColumnType("TEXT")
                        .HasColumnName("pasta_preview");

                    b.Property<int>("Posicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("posicao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<string>("UltimaAssinaturaHistorico")
                        .HasColumnType("TEXT")
                        .HasColumnName("ultima_assinatura_historico");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .HasDatabaseName("idx_maquinas_host");

                    b.ToTable("maquinas", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Molde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.ToTable("moldes", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldeArte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<int>("MoldeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("molde_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("MoldeId");

                    b.ToTable("molde_artes", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldeArtePeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Ajuste")
                        .HasColumnType("TEXT")
                        .HasColumnName("ajuste");

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("arquivo");

                    b.Property<int>("ArteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("arte_id");

                    b.Property<string>("NomeOriginal")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_original");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("papel");

                    b.HasKey("Id");

                    b.HasIndex("ArteId");

                    b.ToTable("molde_arte_pecas", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldePeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Altura")
                        .HasColumnType("REAL")
                        .HasColumnName("altura");

                    b.Property<string>("Contorno")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contorno");

                    b.Property<string>("Furos")
                        .HasColumnType("TEXT")
                        .HasColumnName("furos");

                    b.Property<double>("Largura")
                        .HasColumnType("REAL")
                        .HasColumnName("largura");

                    b.Property<int>("MoldeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("molde_id");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<string>("Origem")
                        .HasColumnType("TEXT")
                        .HasColumnName("origem");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("papel");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("quantidade");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("único")
                        .HasColumnName("tamanho");

                    b.HasKey("Id");

                    b.HasIndex("MoldeId");

                    b.ToTable("molde_pecas", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.OrdemDeServico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("Maquina")
                        .HasColumnType("TEXT")
                        .HasColumnName("maquina");

                    b.Property<double?>("Metros")
                        .HasColumnType("REAL")
                        .HasColumnName("metros");

                    b.Property<string>("NomeDoCliente")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_do_cliente");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<string>("Operador")
                        .HasColumnType("TEXT")
                        .HasColumnName("operador");

                    b.Property<string>("TamanhoDeImpressao")
                        .HasColumnType("TEXT")
                        .HasColumnName("tamanho_de_impressao");

                    b.Property<string>("Tecido")
                        .HasColumnType("TEXT")
                        .HasColumnName("tecido");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("idx_ordens_de_servico_data");

                    b.ToTable("ordens_de_servico", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.OrdemDeServicoImagem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<byte[]>("Dados")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("dados");

                    b.Property<bool>("EhBlusa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eh_blusa");

                    b.Property<string>("NomeDoArquivo")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_do_arquivo");

                    b.Property<string>("OrdemId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ordem_id");

                    b.Property<int>("Posicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("posicao");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantidade");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_mime");

                    b.HasKey("Id");

                    b.HasIndex("OrdemId")
                        .HasDatabaseName("idx_ordens_de_servico_imagens_ordem");

                    b.ToTable("ordens_de_servico_imagens", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Pedido", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("aberto")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.PedidoItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double?>("ComprimentoDeImpressao")
                        .HasColumnType("REAL")
                        .HasColumnName("comprimento_de_impressao");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DataNaCalandra")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_na_calandra");

                    b.Property<string>("MaquinaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("maquina_id");

                    b.Property<string>("MotivoNaCalandra")
                        .HasColumnType("TEXT")
                        .HasColumnName("motivo_na_calandra");

                    b.Property<string>("MotivoPersonalizadoNaCalandra")
                        .HasColumnType("TEXT")
                        .HasColumnName("motivo_personalizado_na_calandra");

                    b.Property<string>("NomeDaMaquina")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_da_maquina");

                    b.Property<string>("NomeDoCliente")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_do_cliente");

                    b.Property<string>("OrdemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ordem_id");

                    b.Property<string>("PedidoId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pedido_id");

                    b.Property<int>("Posicao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("posicao");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("registro_id");

                    b.Property<string>("StatusNaCalandra")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pendente")
                        .HasColumnName("status_na_calandra");

                    b.Property<string>("Tarefa")
                        .HasColumnType("TEXT")
                        .HasColumnName("tarefa");

                    b.Property<string>("Tecido")
                        .HasColumnType("TEXT")
                        .HasColumnName("tecido");

                    b.HasKey("Id");

                    b.HasIndex("OrdemId");

                    b.HasIndex("RegistroId")
                        .HasDatabaseName("idx_pedido_itens_registro");

                    b.HasIndex("PedidoId", "Posicao")
                        .HasDatabaseName("idx_pedido_itens_pedido");

                    b.ToTable("pedido_itens", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<double?>("Espaco")
                        .HasColumnType("REAL")
                        .HasColumnName("espaco");

                    b.Property<string>("Giro")
                        .HasColumnType("TEXT")
                        .HasColumnName("giro");

                    b.Property<double?>("LarguraTecido")
                        .HasColumnType("REAL")
                        .HasColumnName("largura_tecido");

                    b.Property<double?>("Margem")
                        .HasColumnType("REAL")
                        .HasColumnName("margem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("idx_projetos_cliente");

                    b.ToTable("projetos", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.ProjetoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.ToTable("projeto_clientes", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.ProjetoPeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Altura")
                        .HasColumnType("REAL")
                        .HasColumnName("altura");

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("arquivo");

                    b.Property<double>("Largura")
                        .HasColumnType("REAL")
                        .HasColumnName("largura");

                    b.Property<string>("Miniatura")
                        .HasColumnType("TEXT")
                        .HasColumnName("miniatura");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("projeto_id");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId")
                        .HasDatabaseName("idx_projeto_pecas_projeto");

                    b.ToTable("projeto_pecas", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.RegistroDeImpressao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("AreaDeImpressao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0)
                        .HasColumnName("area_de_impressao");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CanaisDeTinta")
                        .HasColumnType("TEXT")
                        .HasColumnName("canais_de_tinta");

                    b.Property<bool>("Cancelada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelada");

                    b.Property<bool>("ComErro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("com_erro");

                    b.Property<double>("ComprimentoDeImpressao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0)
                        .HasColumnName("comprimento_de_impressao");

                    b.Property<double?>("Concluido")
                        .HasColumnType("REAL")
                        .HasColumnName("concluido");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("DataHora")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_hora");

                    b.Property<bool>("EhRecorteOuMosaico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eh_recorte_ou_mosaico");

                    b.Property<string>("EstadoDoProgresso")
                        .HasColumnType("TEXT")
                        .HasColumnName("estado_do_progresso");

                    b.Property<string>("Hora")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora");

                    b.Property<double?>("HorasDecorridas")
                        .HasColumnType("REAL")
                        .HasColumnName("horas_decorridas");

                    b.Property<string>("MaquinaId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("maquina_id");

                    b.Property<bool>("MetricaEstimada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("metrica_estimada");

                    b.Property<string>("NomeDaMaquina")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_da_maquina");

                    b.Property<int?>("Passada")
                        .HasColumnType("INTEGER")
                        .HasColumnName("passada");

                    b.Property<double?>("PercentualDeProgresso")
                        .HasColumnType("REAL")
                        .HasColumnName("percentual_de_progresso");

                    b.Property<string>("ReferenciaDePreview")
                        .HasColumnType("TEXT")
                        .HasColumnName("referencia_de_preview");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Tarefa")
                        .HasColumnType("TEXT")
                        .HasColumnName("tarefa");

                    b.Property<int>("TempoSegundos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("tempo_segundos");

                    b.Property<bool>("TintaExperimental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("tinta_experimental");

                    b.Property<double>("TintaMl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0)
                        .HasColumnName("tinta_ml");

                    b.Property<string>("TipoDeOrigem")
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_de_origem");

                    b.Property<double?>("Total")
                        .HasColumnType("REAL")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("idx_registros_data");

                    b.HasIndex("MaquinaId", "Data")
                        .HasDatabaseName("idx_registros_maquina_data");

                    b.ToTable("registros_de_impressao", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldeArte", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.Molde", "Molde")
                        .WithMany("Artes")
                        .HasForeignKey("MoldeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Molde");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldeArtePeca", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.MoldeArte", "Arte")
                        .WithMany("Pecas")
                        .HasForeignKey("ArteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arte");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldePeca", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.Molde", "Molde")
                        .WithMany("Pecas")
                        .HasForeignKey("MoldeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Molde");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.OrdemDeServicoImagem", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.OrdemDeServico", "Ordem")
                        .WithMany("Imagens")
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordem");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.PedidoItem", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.OrdemDeServico", "Ordem")
                        .WithMany()
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OptimizePro.Data.Entidades.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordem");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Projeto", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.ProjetoCliente", "Cliente")
                        .WithMany("Projetos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.ProjetoPeca", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.Projeto", "Projeto")
                        .WithMany("Pecas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.RegistroDeImpressao", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.Maquina", "Maquina")
                        .WithMany("Registros")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Maquina", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Molde", b =>
                {
                    b.Navigation("Artes");

                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldeArte", b =>
                {
                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.OrdemDeServico", b =>
                {
                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Projeto", b =>
                {
                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.ProjetoCliente", b =>
                {
                    b.Navigation("Projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
