// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptimizePro.Data;

#nullable disable

namespace OptimizePro.Data.Migrations
{
    [DbContext(typeof(OptimizeDbContext))]
    [Migration("20260901155656_AdicionaConfiguracaoApp")]
    partial class AdicionaConfiguracaoApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OptimizePro.Data.Entidades.ConfiguracaoApp", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("TEXT")
                        .HasColumnName("chave");

                    b.Property<string>("Valor")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("Chave");

                    b.ToTable("configuracao_app", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.EncaixeGuardado", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("TEXT")
                        .HasColumnName("chave");

                    b.Property<double?>("Aproveitamento")
                        .HasColumnType("REAL")
                        .HasColumnName("aproveitamento");

                    b.Property<string>("Assinatura")
                        .HasColumnType("TEXT")
                        .HasColumnName("assinatura");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<double>("Consumo")
                        .HasColumnType("REAL")
                        .HasColumnName("consumo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<double?>("Espaco")
                        .HasColumnType("REAL")
                        .HasColumnName("espaco");

                    b.Property<double?>("LarguraTecido")
                        .HasColumnType("REAL")
                        .HasColumnName("largura_tecido");

                    b.Property<double?>("Margem")
                        .HasColumnType("REAL")
                        .HasColumnName("margem");

                    b.Property<string>("PecasJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("pecas");

                    b.Property<string>("PosicoesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("posicoes");

                    b.Property<string>("Receita")
                        .HasColumnType("TEXT")
                        .HasColumnName("receita");

                    b.HasKey("Chave");

                    b.ToTable("encaixe_guardados", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.EncaixeHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double?>("Aproveitamento")
                        .HasColumnType("REAL")
                        .HasColumnName("aproveitamento");

                    b.Property<string>("Assinatura")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assinatura");

                    b.Property<double?>("Consumo")
                        .HasColumnType("REAL")
                        .HasColumnName("consumo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<double?>("LarguraTecido")
                        .HasColumnType("REAL")
                        .HasColumnName("largura_tecido");

                    b.Property<int?>("Pecas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pecas");

                    b.Property<string>("Receita")
                        .HasColumnType("TEXT")
                        .HasColumnName("receita");

                    b.Property<int?>("Tentativas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tentativas");

                    b.HasKey("Id");

                    b.ToTable("encaixe_historico", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.EncaixeReceita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Assinatura")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assinatura");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Receita")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("receita");

                    b.Property<int>("Usos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("usos");

                    b.Property<int>("Vitorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("vitorias");

                    b.HasKey("Id");

                    b.HasIndex("Assinatura", "Receita")
                        .IsUnique();

                    b.ToTable("encaixe_receitas", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Molde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.ToTable("moldes", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldeArte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<int>("MoldeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("molde_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("MoldeId");

                    b.ToTable("molde_artes", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldeArtePeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Ajuste")
                        .HasColumnType("TEXT")
                        .HasColumnName("ajuste");

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("arquivo");

                    b.Property<int>("ArteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("arte_id");

                    b.Property<string>("NomeOriginal")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_original");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("papel");

                    b.HasKey("Id");

                    b.HasIndex("ArteId");

                    b.ToTable("molde_arte_pecas", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldePeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Altura")
                        .HasColumnType("REAL")
                        .HasColumnName("altura");

                    b.Property<string>("Contorno")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contorno");

                    b.Property<string>("Furos")
                        .HasColumnType("TEXT")
                        .HasColumnName("furos");

                    b.Property<double>("Largura")
                        .HasColumnType("REAL")
                        .HasColumnName("largura");

                    b.Property<int>("MoldeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("molde_id");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<string>("Origem")
                        .HasColumnType("TEXT")
                        .HasColumnName("origem");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("papel");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("quantidade");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("único")
                        .HasColumnName("tamanho");

                    b.HasKey("Id");

                    b.HasIndex("MoldeId");

                    b.ToTable("molde_pecas", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<double?>("Espaco")
                        .HasColumnType("REAL")
                        .HasColumnName("espaco");

                    b.Property<string>("Giro")
                        .HasColumnType("TEXT")
                        .HasColumnName("giro");

                    b.Property<double?>("LarguraTecido")
                        .HasColumnType("REAL")
                        .HasColumnName("largura_tecido");

                    b.Property<double?>("Margem")
                        .HasColumnType("REAL")
                        .HasColumnName("margem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("idx_projetos_cliente");

                    b.ToTable("projetos", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.ProjetoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.ToTable("projeto_clientes", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.ProjetoPeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Altura")
                        .HasColumnType("REAL")
                        .HasColumnName("altura");

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("arquivo");

                    b.Property<double>("Largura")
                        .HasColumnType("REAL")
                        .HasColumnName("largura");

                    b.Property<string>("Miniatura")
                        .HasColumnType("TEXT")
                        .HasColumnName("miniatura");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("projeto_id");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId")
                        .HasDatabaseName("idx_projeto_pecas_projeto");

                    b.ToTable("projeto_pecas", (string)null);
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldeArte", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.Molde", "Molde")
                        .WithMany("Artes")
                        .HasForeignKey("MoldeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Molde");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldeArtePeca", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.MoldeArte", "Arte")
                        .WithMany("Pecas")
                        .HasForeignKey("ArteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arte");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldePeca", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.Molde", "Molde")
                        .WithMany("Pecas")
                        .HasForeignKey("MoldeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Molde");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Projeto", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.ProjetoCliente", "Cliente")
                        .WithMany("Projetos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.ProjetoPeca", b =>
                {
                    b.HasOne("OptimizePro.Data.Entidades.Projeto", "Projeto")
                        .WithMany("Pecas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Molde", b =>
                {
                    b.Navigation("Artes");

                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.MoldeArte", b =>
                {
                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.Projeto", b =>
                {
                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("OptimizePro.Data.Entidades.ProjetoCliente", b =>
                {
                    b.Navigation("Projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
